apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper
  template:
    metadata:
      labels:
        app: gatekeeper
    spec:
      containers:
      - name: gatekeeper
        image: yoiksoft/gatekeeper:v1.0.2
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-creds
              key: bot-token
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-storage
            mountPath: "/data"
      initContainers:
        - name: redis-data-permissions-fix
          image: busybox
          command: ["/bin/chmod","-R","777","/redis-data"]
          volumeMounts:
            - name: redis-storage
              mountPath: "/redis-data"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-storage-claim
