apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage